import React, { useState, useEffect, useContext } from 'react'
import { adminSocket, playerSocket } from '../socket';
import { ContextAPI } from '../Context';
// will have a useState variable when it these were generated by ai
export const allQuestions = [

    {
        qno: 2,
        question: "Which HTML tag is used to define an unordered list?",
        options: ["<ol>", "<ul>", "<li>", "<list>"],
        correctIndex: 1,
        explanation: "<ul> defines an unordered list; <ol> is ordered and <li> is a list item."
    },
    {
        qno: 3,
        question: "What is the value of 2 + '2' in JavaScript?",
        options: ["4", "'22'", "NaN", "undefined"],
        correctIndex: 1,
        explanation: "When adding a number and a string, JavaScript coerces the number to string and concatenates, resulting in '22'."
    },
    {
        qno: 4,
        question: "Which data structure uses FIFO (First In First Out)?",
        options: ["Stack", "Queue", "Tree", "Graph"],
        correctIndex: 1,
        explanation: "A Queue follows FIFO order: the first element added is the first removed."
    },
    {
        qno: 5,
        question: "What does CSS stand for?",
        options: ["Computer Style Sheets", "Cascading Style Sheets", "Creative Style System", "Cascading Simple Sheets"],
        correctIndex: 1,
        explanation: "CSS stands for Cascading Style Sheets, used for styling HTML."
    },
    {
        qno: 6,
        question: "Which HTTP status code means 'Not Found'?",
        options: ["200", "301", "404", "500"],
        correctIndex: 2,
        explanation: "404 is the standard HTTP response code indicating the requested resource was not found."
    },
    {
        qno: 7,
        question: "What is the derivative of x^2?",
        options: ["2x", "x", "x^2", "1"],
        correctIndex: 0,
        explanation: "Using basic differentiation, d/dx(x^2) = 2x."
    },
    {
        qno: 8,
        question: "Which keyword is used to create an immutable variable in JavaScript?",
        options: ["var", "let", "const", "immutable"],
        correctIndex: 2,
        explanation: "const declares a variable whose binding cannot be reassigned (immutable reference)."
    },
    {
        qno: 9,
        question: "In Git, which command creates a new branch?",
        options: ["git checkout -b <name>", "git push origin <name>", "git merge <name>", "git init <name>"],
        correctIndex: 0,
        explanation: "git checkout -b <name> creates and switches to a new branch in a single step. (Alternatively git branch <name> then checkout.)"
    },
    {
        qno: 10,
        question: "Which algorithmic time complexity is better (faster) for large n?",
        options: ["O(n^2)", "O(n log n)", "O(2^n)", "O(n!)"],
        correctIndex: 1,
        explanation: "O(n log n) grows much slower than O(n^2), O(2^n), or O(n!), so it's better for large inputs."
    }

];

const Admin = () => {
    //const [play, setPlay] = useState(false);
    const [hostName, setHostName] = useState("");
    const [quizTime, setQuizTime] = useState("");
    const [roomCode, setRoomCode] = useState("");
   // const [players, setPlayers] = useState([]);
    //const [leaderBoardData, setLeaderBoardData] = useState([]);
     const {players,leaderBoardData,setPlay} = useContext(ContextAPI);
    useEffect(() => {
        playerSocket.on("updatePlayers", (players) => setPlayers(players));

        playerSocket.on("leaderboardUpdate", (details) =>
            setLeaderBoardData(details)
        );

        return () => {
            playerSocket.off("leaderboardUpdate");
            playerSocket.off("updatePlayers");
        };
    }, []);

    const createQuiz = () => {
        if (!hostName || !quizTime)
            return alert("Enter host name AND quiz time!");

        adminSocket.emit(
            "createRoom",
            { hostName, quizTime },
            (response) => {
                if (response.roomCode) setRoomCode(response.roomCode);
                else alert("Error creating room!");
            }
        );
    };


    const startAutoQuestionFlow = () => {
        const totalQ = allQuestions.length;
        const totalTimeSec = quizTime * 60;

        const perQuestionTime = Math.floor(totalTimeSec / totalQ);

        console.log("Time per question:", perQuestionTime);

        let index = 0;


        sendQuestion(allQuestions[index]);
        index++;


        const interval = setInterval(() => {
            if (index >= totalQ) {
                clearInterval(interval);
                console.log("All questions sent!");
                return;
            }

            sendQuestion(allQuestions[index]);
            index++;
        }, perQuestionTime * 1000);
    };

    const playQuiz = () => {
        if (!roomCode) return alert("Room not created");

        adminSocket.emit("playOnOff", { roomCode, play: true }, (res) => {
            console.log(res);
        });
        setPlay(true);
        startAutoQuestionFlow();
    };

    // send question to backend
    const sendQuestion = (questionObj) => {
        adminSocket.emit(
            "sendQuestion",
            { roomCode, question: questionObj },
            (res) => {
                console.log("Question sent:", questionObj.qno, res);

            }
        );
    };

    return (
        <div className='h-screen flex justify-center items-center'>
            <div className='flex flex-col gap-3'>

                {/* CREATE ROOM */}
                {!roomCode && (
                    <div className='flex flex-col gap-2'>
                        <input
                            placeholder='Enter host name'
                            value={hostName}
                            onChange={(e) => setHostName(e.target.value)}
                        />
                        <input
                            placeholder='Enter quiz time in minutes'
                            value={quizTime}
                            type="number"
                            onChange={(e) => setQuizTime(e.target.value)}
                        />
                        <button onClick={createQuiz}>Create Quiz</button>
                    </div>
                )}

                {/* SHOW ROOM */}
                {roomCode && (
                    <div className="text-xl">Room Code: {roomCode}</div>
                )}

                {/* START BUTTON */}
                {roomCode && !play && (
                    <button onClick={playQuiz}>Start Quiz</button>
                )}

                {/* SHOW PLAYERS */}
                <div>
                    <h3>Players Joined:</h3>
                    {players.map((p) => (
                        <div >{p}</div>
                    ))}
                </div>

            </div>
        </div>
    );
};

export default Admin;
